stages:
  - transfer

transfer-image:
  image:
    name: alpine:latest  # Change base image to Alpine (lightweight & supports apk)
    entrypoint: [""]
  stage: transfer
  variables:
    IMAGE_SOURCE: "registry.gitlab.com/$CI_PROJECT_PATH/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG"
    IMAGE_TARGET: "$JFROG_REGISTRY/$JFROG_REPO/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG"
  before_script:
    - apk add --no-cache crane  # Install Crane
    - echo "Authenticating with GitLab and JFrog"
    - echo "{\"auths\":{\"registry.gitlab.com\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}, \"$JFROG_REGISTRY\":{\"username\":\"$JFROG_USER\",\"password\":\"$JFROG_PASSWORD\"}}}" > ~/.docker/config.json

  script:
    - echo "Pulling image from GitLab: $IMAGE_SOURCE"
    - crane pull $IMAGE_SOURCE image.tar

    - echo "Pushing image to JFrog: $IMAGE_TARGET"
    - crane push image.tar $IMAGE_TARGET

  only:
    - main  # Change this to your desired branch
