transfer_image:
  image: gcr.io/kaniko-project/executor:latest
  stage: transfer
  dependencies:
    - build_image
  script:
    - export BASE_IMAGE=$(cat image_tag.txt)
    - echo "FROM $BASE_IMAGE" > Dockerfile
    - mkdir -p /kaniko/.docker
    - echo '{ "auths": { "registry.gitlab.com": { "auth": "'$(echo -n "$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD" | base64 -w 0)'" }, "mycompany.jfrog.io": { "auth": "'$(echo -n "$JFROG_USER:$JFROG_PASSWORD" | base64 -w 0)' } } }' > /kaniko/.docker/config.json
    - echo "Using image tag: $IMAGE_TAG"
    - /kaniko/executor --dockerfile Dockerfile --context dir:///workspace --destination $JFROG_IMAGE:$IMAGE_TAG
