image: debian:latest  # Use a Debian-based image (or switch to Fedora for better Podman support)

stages:
  - build
  - push

variables:
  IMAGE_NAME: "myapp"
  IMAGE_TAG: "$CI_COMMIT_REF_SLUG"
  REGISTRY: "$CI_REGISTRY"
  CONTAINER_RUNTIME: "podman"
  XDG_RUNTIME_DIR: "/run/user/$(id -u)"  # Ensures rootless Podman works

before_script:
  - apt-get update && apt-get install -y podman  # Install Podman
  - podman --version  # Check Podman version

build:
  stage: build
  script:
    - podman build -t $IMAGE_NAME:$IMAGE_TAG .
    - podman images  # Verify the built image

push:
  stage: push
  script:
    - echo "$CI_REGISTRY_PASSWORD" | podman login -u "$CI_REGISTRY_USER" --password-stdin $REGISTRY
    - podman tag $IMAGE_NAME:$IMAGE_TAG $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
    - podman push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
