USER-SUPPLIED VALUES:
gitlabUrl: http://gitlab.com
rbac:
  create: true
runnerRegistrationToken: glrt-AH5vTUbj5PX7aH9giXtj
runnerTags: k8s-runner
runners:
  config: |
    [[runners]]
      name = "k8s-runner"
      url = "http://gitlab.com"
      token = "glrt-AH5vTUbj5PX7aH9giXtj"
      executor = "kubernetes"
      [runners.kubernetes]
        image = "docker:latest"
        privileged = true
        [runners.kubernetes.volumes]
          [[runners.kubernetes.volumes.host_path]]
            name = "docker-socket"
            mount_path = "/var/run/docker.sock"
            host_path = "/var/run/docker.sock"
serviceAccountName: gitlab-runner-sa
