apiVersion: v3
kind: service
metadata:
  name: my-service-name
  description: This service handles business logic for the checkout process.
  displayName: my-service-name
  tags:
    - servicetype:webapp
    - team:devops
  owner: team-devops
  links:
    - name: source_code
      type: repo
      provider: github
      url: https://github.com/myorg/my-service
    - name: docs
      type: doc
      provider: confluence
      url: https://confluence.myorg.com/pages/my-service-docs
    - name: monitoring
      type: dashboard
      provider: datadog
      url: https://app.datadoghq.com/dashboard/abc-123
  contacts:
    - name: Mike 
      type: email
      contact: mark.meeker@hyatt.com
    - name: Heather Riddle
      type: slack
      contact: https://your-slack-workspace.slack.com/app_redirect?channel=channel-id
  additionalOwners:
    - name: Mike Craig
      type: Manager
    - name: Bob Stevenson
      type: Devops

datadog:
  pipelines:
    fingerprints:
      - abc123def456
      - xyz789ghi000

spec:
  lifecycle: production
  tier: high
  languages:
    - python
    - bash
    - javascript
  type: web
  dependsOn:
    - service:auth-api
    - service:payment-gateway
  componentOf:
    - service:checkout
