apiVersion: v3
kind: service
metadata:
  service_name: jay-test-svc
  service_description: This service handles business logic for the checkout process.
  service_displayName: my-service-name
  service_tags:
    - servicetype:webapp
    - team:devops
  service_owner: team-devops
  links:
    - service_link_name: source_code
      service_link_type: repo
      service_link_provider: github
      service_link_url: https://github.com/myorg/my-service
    - service_link_name: docs
      service_link_type: doc
      service_link_provider: confluence
      service_link_url: https://confluence.myorg.com/pages/my-service-docs
    - service_link_name: monitoring
      service_link_type: dashboard
      service_link_provider: datadog
      service_link_url: https://app.datadoghq.com/dashboard/abc-123
  contacts:
    - service_contact_name: Mike 
      service_contact_type: email
      service_contact_contact: mark.meeker@hyatt.com
    - service_contact_name: Heather Riddle
      service_contact_type: slack
      service_contact_contact: https://your-slack-workspace.slack.com/app_redirect?channel=channel-id
  additionalOwners:
    - service_additionalOwner_name: Mike Craig
      service_additionalOwner_type: Manager
    - service_additionalOwner_name: Bob Stevenson
      service_additionalOwner_type: Devops

datadog:
  service_pipelines:
    service_fingerprints:
      - abc123def456
      - xyz789ghi000

spec:
  service_lifecycle: production
  service_tier: high
  service_languages:
    - python
    - bash
    - javascript
  service_type: web
  service_dependsOn:
    - service:auth-api
    - service:payment-gateway
  service_componentOf:
    - service:checkout
