stages:
  - generate-json
  - sc-datadog

generate_json:
  stage: generate-json
  image: python:3.11
  script:
    - python3 sc.py >  service_info.json
  artifacts:
    paths:
      - service_info.json
    expire_in: 1 hour

send_datadog_service:
  stage: sc-datadog
  image: curlimages/curl:latest
  script:
    - echo "Sending service definition to Datadog Service Catalog"
    - |
      curl -X POST "https://api.datadoghq.com/api/v2/catalog/entity" \
        -H "Content-Type: application/json" \
        -H "DD-API-KEY: $SC_DD_API_KEY" \
        -H "DD-APPLICATION-KEY: $SC_DD_APP_KEY" \
        -H "DD-ORIGIN: cicd" \
        -H "DD-ORIGIN-DETAIL: curl" \
        -d @service_info.json \
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - changes:
        - service_info.txt
      when: always  
    
