stages:
  - build
  - push

variables:
  IMAGE_NAME: registry.example.com/your-project/node-alpine

build_and_push:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  parallel:
    matrix:
      - NODE_DIR: ["node-17/alpine-3.18", "node-18/alpine-3.18", "node-20/alpine-3.18"]
  script:
    - NODE_VERSION=$(echo $NODE_DIR | cut -d'-' -f2 | cut -d'/' -f1)
    - echo docker build  -t $IMAGE_NAME:$NODE_VERSION -f $NODE_DIR/Dockerfile .
    - echo docker push $IMAGE_NAME:$NODE_VERSION
  only:
    - main
  tags:
    - k8s-runner
