stages:
  - build
variables:
  ARTIFACTORY_USER: 2501440
  ARTIFACTORY_URL: "https://docker.hyattdev.com"
  IMAGE_NAME: docker.hyattdev.com/docker/alpine-node
  
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  parallel:
    matrix:
      #- NODE_DIR: ["18/alpine3.20", "18/alpine3.21", "20/alpine3.20", "20/alpine3.21", "22/alpine3.20", "22/alpine3.21"]
      - NODE_DIR: ${NODE_DIRS}
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$ARTIFACTORY_URL\":{\"username\":\"$ARTIFACTORY_USER\",\"password\":\"$ARTIFACTORY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - export NODE_DIRS=$(find . -name Dockerfile | sed 's|/Dockerfile||' | awk '{print "\"" $0 "\""}' ORS=',' | sed 's/,$//')
    - echo Detected NODE_DIRS are  -  $NODE_DIRS   

  script: 
    - echo "CI_PROJECT_DIR - ${CI_PROJECT_DIR}"
    - echo "NODE_DIR - ${NODE_DIR}"
    - echo "Checking Dockerfile Path - ${CI_PROJECT_DIR}/${NODE_DIR}/Dockerfile"
    - ls -al "${CI_PROJECT_DIR}/${NODE_DIR}"
    # - echo "${ARTIFACTORY_PASSWORD}" | docker login ${ARTIFACTORY_URL} -u "${ARTIFACTORY_USER}" --password-stdin
    - NODE_VERSION=$(awk '/ENV NODE_VERSION/{print $3}' $NODE_DIR/Dockerfile | tr -d '[:space:]') 
    - echo  "NODE_VERSION - ${NODE_VERSION}"
    - ALPINE_VERSION=$(echo $NODE_DIR | cut -d'/' -f2) # Extract alpine version (3.18, 3.19, 3.20)
    - FINAL_IMAGE="$IMAGE_NAME:node-${NODE_VERSION}-${ALPINE_VERSION}" # Construct the final tag
    - echo Building image - "$FINAL_IMAGE"
    - echo docker build -t "$FINAL_IMAGE" -f "$NODE_DIR/Dockerfile"
    - ls -a /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - export DOCKER_AUTH_CONFIG=/kaniko/.docker

    ## Run Kaniko to build and push
    # - mkdir -p /kaniko/.docker
    # - echo "{\"auths\":{\"$ARTIFACTORY_URL\":{\"username\":\"$ARTIFACTORY_USER\",\"password\":\"$ARTIFACTORY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/${NODE_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/${NODE_DIR}/Dockerfile"
      --destination "${FINAL_IMAGE}" 


  



