stages:
  - build
  - push

variables:
  IMAGE_NAME: registry.example.com/your-project/node-alpine

build_and_push:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  parallel:
    matrix:
      - NODE_DIR: ["17/alpine-3.18", "18/alpine-3.18", "20/alpine-3.18"]
  script:
    - NODE_VERSION=$(awk -F'=' '/ENV NODE_VERSION/{print $2}' $NODE_DIR/Dockerfile | tr -d '[:space:]') # Using awk to extract NODE_VERSION # Extract node version (17, 18, 20)
    - ALPINE_VERSION=$(echo $NODE_DIR | cut -d'/' -f2) # Extract alpine version (3.18, 3.19, 3.20)
    - FINAL_IMAGE="$IMAGE_NAME:node-${NODE_VERSION}-${ALPINE_VERSION}" # Construct the final tag
    - echo Building image - "$FINAL_IMAGE"
    - echo docker build -t "$FINAL_IMAGE" -f "$NODE_DIR/Dockerfile" .
    - echo Pushing image -  "$FINAL_IMAGE"
    - echo docker push "$FINAL_IMAGE"
  only:
    - main
  tags:
    - k8s-runner
