stages:
  - build


build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  parallel:
    matrix:
      - NODE_DIR: ["17/alpine3.18", "18/alpine3.18", "20/alpine3.18"]
  script: 
    - echo "${CI_REGISTRY_PASSWORD}" | docker login registry.pgr.com -u "${CI_REGISTRY_USER}" --password-stdin
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/${NODE_DIR}/Dockerfile"
      --destination "registry.pgr.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}-${NODE_DIR}"
