stages:
  - build
variables:
  ARTIFACTORY_USER: 2501440
  ARTIFACTORY_URL: "https://docker.hyattdev.com"
  #IMAGE_NAME: docker.hyattdev.com/docker/alpine-node
  IMAGE_NAME: docker.hyattdev.com/docker/gitlab-poc/base-images/alpine
  

  
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  parallel:
    matrix:
      - NODE_DIR: ["alpine3.2.0"]

  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$ARTIFACTORY_URL\":{\"username\":\"$ARTIFACTORY_USER\",\"password\":\"$ARTIFACTORY_PASSWORD\"}}}" > /kaniko/.docker/config.json

  script: 
    - | 
    - echo "CI_PROJECT_DIR - ${CI_PROJECT_DIR}"
    - echo "NODE_DIR - ${NODE_DIR}"
    - echo "Checking Dockerfile Path - ${CI_PROJECT_DIR}/${NODE_DIR}/Dockerfile"
    - ls -al "${CI_PROJECT_DIR}/${NODE_DIR}"
    - ALPINE_VERSION=$(cat ${NODE_DIR}/Dockerfile | awk '/^FROM/ {print $2}') 
    - FINAL_IMAGE="${IMAGE_NAME}/${ALPINE_VERSION}" # Construct the final tag
    - echo Building image - "$FINAL_IMAGE"
    - echo docker build -t "$FINAL_IMAGE" -f "$NODE_DIR/Dockerfile"
    - ls -a /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - export DOCKER_AUTH_CONFIG=/kaniko/.docker

    # Run Kaniko to build and push
    # - mkdir -p /kaniko/.docker
    # - echo "{\"auths\":{\"$ARTIFACTORY_URL\":{\"username\":\"$ARTIFACTORY_USER\",\"password\":\"$ARTIFACTORY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/${NODE_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/${NODE_DIR}/Dockerfile"
      --destination "${FINAL_IMAGE}"
 



  


