apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-runner-sa-test
  namespace: gitlab-runner
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-runner-role-test
  namespace: gitlab-runner
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "secrets", "configmaps"]
    verbs: ["get", "watch", "list", "create", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-runner-binding-test
  namespace: gitlab-runner
subjects:
  - kind: ServiceAccount
    name: gitlab-runner-sa-test
    namespace: gitlab-runner
roleRef:
  kind: Role
  name: gitlab-runner-role
  apiGroup: rbac.authorization.k8s.io
---
